# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: "0.2.5"

package:
  name: yamlium
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/y/yamlium/yamlium-${{ version }}.tar.gz
    sha256: 4e72b1978d27a069d1eb01300c93239e77b13c26cf14a38b5819e0002f90d9aa

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - yamlium
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  homepage: https://github.com/erikmunkby/yamlium
  summary: Fast, modern yaml parser and manipulator
  description: A high-performance, dependency-free YAML parser for Python that preserves all YAML features including comments, anchors, and formatting.
  license: MIT
  license_file: LICENSE
  documentation: https://github.com/erikmunkby/yamlium

extra:
  recipe-maintainers:
    - carlodri
