# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
context:
  version: "0.2.2"

package:
  name: yamlium
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/y/yamlium/yamlium-${{ version }}.tar.gz
    sha256: 332c34d0dd6bd4245005b2f7e468edb826f3a4132597bd70cf8e088ed49b269c

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - yamlium
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  homepage: https://github.com/erikmunkby/yamlium
  summary: Fast, modern yaml parser and manipulator
  description: A high-performance, dependency-free YAML parser for Python that preserves all YAML features including comments, anchors, and formatting.
  license: MIT
  license_file: LICENSE
  documentation: https://github.com/erikmunkby/yamlium

extra:
  recipe-maintainers:
    - carlodri
